### ISSUE TITLE
fatal error: systemd/sd-journal.h: No such file or directory

### ISSUE THREAD

**Issue by joneschakk** [wjoel/mesos-journald-container-logger#3]
Hi there i just ran into the following error:
`journald_container_logger.cpp:23:32: fatal error: systemd/sd-journal.h: No such file or directory
compilation terminated.`
this was during compiling the code is there any workaround

**Comment by wjoel** [comment]
You need to `apt-get install libsystemd-dev` (or similar for your distribution).

**Comment by joneschakk** [comment]
Yes i did add the packages `apt-get install libsystemd-dev`. Since the error was persistent i thought i would run the scripts `build-mesos.sh` and `compile.sh`
Now a different problem comes up
```
[ 20%] Linking CXX executable mesos-journald-container-logger-tests
/usr/bin/ld: cannot find -lgmock
/usr/bin/ld: cannot find -lgmock_main
/usr/bin/ld: cannot find -lgtest
/usr/bin/ld: cannot find -lgtest_main
collect2: error: ld returned 1 exit status
```
i installed the google mock test packages from [googletest](https://github.com/google/googletest.git
)
any thoughts :)

**Comment by wjoel** [comment]
Have you installed all the dependencies in http://mesos.apache.org/documentation/latest/building/?

**Comment by joneschakk** [comment]
Yes I had, actually i did an installation of mesos1.6.0, but currently i had built with the scripts that is in this git repo (mesos-journald-container-logger)

**Comment by joneschakk** [comment]
Hey thanks a lot for your support, after a lot searching found place which detailed on how to install packages for gtest and gmock. Problem solved for good. 
But how can i take out the logs from systemd

**Comment by wjoel** [comment]
Glad it worked out for you! Forwarding logs from systemd is outside of the scope of this project, but you can [forward the logs to rsyslog](https://wiki.archlinux.org/index.php/rsyslog#journald.27s_syslog-forward_feature) and then let rsyslog forward logs to whatever centralized log system you use. See also https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/s1-interaction_of_rsyslog_and_journal
